INSERT INTO files (name) VALUES ('media/3. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (14).avif');
INSERT INTO files (name) VALUES ('media/1. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc.avif');
INSERT INTO files (name) VALUES ('media/7. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (9).avif');
INSERT INTO files (name) VALUES ('media/2. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (10).avif');
INSERT INTO files (name) VALUES ('media/4. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (11).avif');
INSERT INTO files (name) VALUES ('media/5. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (12).avif');
INSERT INTO files (name) VALUES ('media/8. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (13).avif');
INSERT INTO files (name) VALUES ('media/6. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (8).avif');
INSERT INTO files (name) VALUES ('media/9. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (1).avif');
INSERT INTO files (name) VALUES ('media/10. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (15).avif');
INSERT INTO files (name) VALUES ('media/11. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (5).avif');
INSERT INTO files (name) VALUES ('media/12. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (2).avif');
INSERT INTO files (name) VALUES ('media/14. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (7).avif');
INSERT INTO files (name) VALUES ('media/Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (3).avif');
INSERT INTO files (name) VALUES ('media/13. Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (6).avif');
INSERT INTO files (name) VALUES ('media/Gia-Up-6-Ly-Inox-Senhome-SH-GL30-Ke-Up-Ly-Co-Khay-Hung-Nuoc (4).avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-Senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-Senhome-3.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-Senhome-2.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-Senhome.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-Senhome-5.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-Senhome-4.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-4.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-2.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-5.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-6.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-3.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-1.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-7.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-8.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-6-ly-coc-inox-304-9.avif');
INSERT INTO files (name) VALUES ('media/6. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/7. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/5. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/3. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/1. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/2. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/4. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/9. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/8. gia-up-8-ly.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-8- ly-coc -inox-304-Senhome-2.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly-inox-304-Senhome-4.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly-inox-304-Senhome.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly-inox-304-Senhome-2.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly-inox-304-Senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly-inox-304-Senhome-3.avif');
INSERT INTO files (name) VALUES ('media/Gia-up-ly-inox-304-Senhome-6.avif');
INSERT INTO files (name) VALUES ('media/gia de ly-04.avif');
INSERT INTO files (name) VALUES ('media/gia de ly-03.avif');
INSERT INTO files (name) VALUES ('media/gia de ly-01.avif');
INSERT INTO files (name) VALUES ('media/gia de ly-02.avif');
INSERT INTO files (name) VALUES ('media/SENHOME FILE THIET KE BANNER.avif');
INSERT INTO files (name) VALUES ('media/banner-senhome official.avif');
INSERT INTO files (name) VALUES ('media/800 X 1778 senhome banner.avif');
INSERT INTO files (name) VALUES ('media/FILE THIET KE BANNER1112.avif');
INSERT INTO files (name) VALUES ('media/351 X 756 senhome banner.avif');
INSERT INTO files (name) VALUES ('media/FILE THIET KE BANNER111.avif');
INSERT INTO files (name) VALUES ('media/3.avif');
INSERT INTO files (name) VALUES ('media/6.avif');
INSERT INTO files (name) VALUES ('media/1.avif');
INSERT INTO files (name) VALUES ('media/2.avif');
INSERT INTO files (name) VALUES ('media/5.avif');
INSERT INTO files (name) VALUES ('media/4.avif');
INSERT INTO files (name) VALUES ('media/7.avif');
INSERT INTO files (name) VALUES ('media/12.avif');
INSERT INTO files (name) VALUES ('media/8.avif');
INSERT INTO files (name) VALUES ('media/10.avif');
INSERT INTO files (name) VALUES ('media/13.avif');
INSERT INTO files (name) VALUES ('media/11.avif');
INSERT INTO files (name) VALUES ('media/14.avif');
INSERT INTO files (name) VALUES ('media/16.avif');
INSERT INTO files (name) VALUES ('media/17.avif');
INSERT INTO files (name) VALUES ('media/15.avif');
INSERT INTO files (name) VALUES ('media/18.avif');
INSERT INTO files (name) VALUES ('media/19.avif');
INSERT INTO files (name) VALUES ('media/22.avif');
INSERT INTO files (name) VALUES ('media/23.avif');
INSERT INTO files (name) VALUES ('media/20.avif');
INSERT INTO files (name) VALUES ('media/25.avif');
INSERT INTO files (name) VALUES ('media/24.avif');
INSERT INTO files (name) VALUES ('media/26.avif');
INSERT INTO files (name) VALUES ('media/27.avif');
INSERT INTO files (name) VALUES ('media/28.avif');
INSERT INTO files (name) VALUES ('media/29.png');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304- 1-tang 65cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304- 2-tang 65cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304- 1-tang 105cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304- 1-tang 95cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304- 2-tang 105cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304- 2-tang 95cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304-2-tang 125cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304-de-bon-rua-da-nang-senhome -1-tang-85cm-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304-de-bon-rua-da-nang-senhome -1-tang-12-new.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-304-1-tang 125cm-de-bon-rua-da-nang-senhome-new.avif');
INSERT INTO files (name) VALUES ('media/senhome-banner phu-ke-chen-bon-rua.avif');
INSERT INTO files (name) VALUES ('media/[[AnhDaiDien 2T]Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-3.3.avif');
INSERT INTO files (name) VALUES ('media/[[AnhDaiDien2T-nghieng]Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-3.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome (2).avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome (5).avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome (6).avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-4.1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome (9).avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome (3).avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-5.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-7.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-10.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-9.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-6.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome-14.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 1-tang 105cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 1-tang 95cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 1-tang 65cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 2-tang 65cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 1-tang 125cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 2-tang 85cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 2-tang 95cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 2-tang 125cm-de-bon-rua-da-nang-senhome-2.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox 2-tang 105cm-de-bon-rua-da-nang-senhome-1.avif');
INSERT INTO files (name) VALUES ('media/Ke-chen-bat-inox-de-bon-rua-da-nang-senhome -1-tang-12.avif');
INSERT INTO files (name) VALUES ('media/12.2 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/2.2 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/3.4 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/12.3  ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/15.1 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/14.2 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/16.1 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/3.3 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/17 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/16 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/2.3 ke-inox-da-nang-nhieu-tang-nha-bep-senhome.avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (2).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (6).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (5).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (1).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (4).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (3).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (9).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (10).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (11).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (8).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (12).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (7).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (14).avif');
INSERT INTO files (name) VALUES ('media/ke-inox-da-nang-nhieu-tang-nha-bep-senhome (13).avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-2.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-1.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-4.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-3.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-5.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-6.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-27.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-23.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-24.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-28.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-25.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-29.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-33.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-31.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-30.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-32.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-34.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-35.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-38.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-36.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-37.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-40.avif');
INSERT INTO files (name) VALUES ('media/ke-de-do-da-nang-nha-bep-39.avif');
