// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
	Username pgtype.Text `json:"username"`
	Password string      `json:"password"`
}
