// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package blog_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID              int64            `json:"id"`
	Title           string           `json:"title"`
	Slug            string           `json:"slug"`
	MetaTitle       string           `json:"meta_title"`
	MetaDescription string           `json:"meta_description"`
	MetaKeywords    string           `json:"meta_keywords"`
	CanonicalUrl    string           `json:"canonical_url"`
	OgTitle         string           `json:"og_title"`
	OgDescription   string           `json:"og_description"`
	OgImage         string           `json:"og_image"`
	File            pgtype.Text      `json:"file"`
	IsActive        bool             `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type PostTag struct {
	Name   string `json:"name"`
	PostID int64  `json:"post_id"`
}
