// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package blog_db

import (
	"context"
)

const bulkDeletePosts = `-- name: BulkDeletePosts :exec
DELETE FROM posts
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeletePosts(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeletePosts, dollar_1)
	return err
}

const countPosts = `-- name: CountPosts :one
SELECT
  COUNT(*)
FROM
  posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO
  posts (title, slug)
VALUES
  ($1, $2)
RETURNING id
`

type CreatePostParams struct {
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPost, arg.Title, arg.Slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPost = `-- name: GetPost :one
SELECT id, title, slug
FROM posts
WHERE id = $1
`

type GetPostRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetPost(ctx context.Context, id int64) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(&i.ID, &i.Title, &i.Slug)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, title, slug
FROM posts
WHERE slug = $1
`

type GetPostBySlugRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i GetPostBySlugRow
	err := row.Scan(&i.ID, &i.Title, &i.Slug)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, title, slug
FROM posts
LIMIT
  $1
OFFSET
  $2
`

type GetPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPostsRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error) {
	rows, err := q.db.Query(ctx, getPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET
  title = $2,
  slug = $3
WHERE
  id = $1
`

type UpdatePostParams struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost, arg.ID, arg.Title, arg.Slug)
	return err
}
