-- +goose Up
-- +goose StatementBegin
ALTER TABLE categories
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE collections
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE products
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE orders
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE customers
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE reviews
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE files
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE pages
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE menus
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE discounts
ALTER COLUMN starts_at TYPE TIMESTAMPTZ,
ALTER COLUMN ends_at TYPE TIMESTAMPTZ,
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE shipping_fees
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
