// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO
  addresses (full_name, phone, email, address_line)
VALUES
  ($1, $2, $3, $4)
RETURNING
  id
`

type CreateAddressParams struct {
	FullName    string      `json:"full_name"`
	Phone       pgtype.Text `json:"phone"`
	Email       pgtype.Text `json:"email"`
	AddressLine string      `json:"address_line"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.AddressLine,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
