// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteCustomers = `-- name: BulkDeleteCustomers :exec
DELETE FROM customers
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeleteCustomers(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteCustomers, dollar_1)
	return err
}

const countCustomers = `-- name: CountCustomers :one
SELECT
  COUNT(*)
FROM
  customers
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO
  customers (name, phone, password, zns_otp)
VALUES
  ($1, $2, $3, $4)
RETURNING
  id
`

type CreateCustomerParams struct {
	Name     string      `json:"name"`
	Phone    string      `json:"phone"`
	Password string      `json:"password"`
	ZnsOtp   pgtype.Text `json:"zns_otp"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Phone,
		arg.Password,
		arg.ZnsOtp,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, phone, email
FROM customers
WHERE id = $1
LIMIT 1
`

type GetCustomerRow struct {
	ID    int64       `json:"id"`
	Name  string      `json:"name"`
	Phone string      `json:"phone"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) GetCustomer(ctx context.Context, id int64) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, phone, password, phone_verified
FROM customers
WHERE phone = $1
LIMIT 1
`

type GetCustomerByPhoneRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Phone         string      `json:"phone"`
	Password      string      `json:"password"`
	PhoneVerified pgtype.Bool `json:"phone_verified"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (GetCustomerByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i GetCustomerByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Password,
		&i.PhoneVerified,
	)
	return i, err
}

const getCustomers = `-- name: GetCustomers :many
SELECT
  id,
  name,
  phone
FROM
  customers
LIMIT
  $1
OFFSET
  $2
`

type GetCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetCustomersRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) GetCustomers(ctx context.Context, arg GetCustomersParams) ([]GetCustomersRow, error) {
	rows, err := q.db.Query(ctx, getCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersRow
	for rows.Next() {
		var i GetCustomersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Phone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    name     = COALESCE($2, name),
    email    = COALESCE($3, email),
    password = CASE WHEN $4 = '' THEN password ELSE $4 END,
    phone_verified = $5
WHERE id = $1
RETURNING id
`

type UpdateCustomerParams struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Email         pgtype.Text `json:"email"`
	Column4       interface{} `json:"column_4"`
	PhoneVerified pgtype.Bool `json:"phone_verified"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Column4,
		arg.PhoneVerified,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const verifyPhone = `-- name: VerifyPhone :exec
UPDATE customers
SET phone_verified = true,
    zns_otp = NULL
WHERE phone = $1 AND zns_otp = $2
`

type VerifyPhoneParams struct {
	Phone  string      `json:"phone"`
	ZnsOtp pgtype.Text `json:"zns_otp"`
}

func (q *Queries) VerifyPhone(ctx context.Context, arg VerifyPhoneParams) error {
	_, err := q.db.Exec(ctx, verifyPhone, arg.Phone, arg.ZnsOtp)
	return err
}
