// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount-condition.sql

package product_db

import (
	"context"
)

const bulkDeleteDiscountConditions = `-- name: BulkDeleteDiscountConditions :exec
DELETE FROM discount_conditions
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteDiscountConditions(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteDiscountConditions, dollar_1)
	return err
}

const createDiscountCondition = `-- name: CreateDiscountCondition :one
INSERT INTO discount_conditions (
  discount_id, condition_type, operator, value
)
VALUES ($1, $2, $3, $4)
RETURNING id, discount_id, condition_type, operator, value
`

type CreateDiscountConditionParams struct {
	DiscountID    int64  `json:"discount_id"`
	ConditionType string `json:"condition_type"`
	Operator      string `json:"operator"`
	Value         string `json:"value"`
}

func (q *Queries) CreateDiscountCondition(ctx context.Context, arg CreateDiscountConditionParams) (DiscountCondition, error) {
	row := q.db.QueryRow(ctx, createDiscountCondition,
		arg.DiscountID,
		arg.ConditionType,
		arg.Operator,
		arg.Value,
	)
	var i DiscountCondition
	err := row.Scan(
		&i.ID,
		&i.DiscountID,
		&i.ConditionType,
		&i.Operator,
		&i.Value,
	)
	return i, err
}

const getDiscountConditions = `-- name: GetDiscountConditions :many
SELECT id, discount_id, condition_type, operator, value FROM discount_conditions WHERE discount_id = $1
`

func (q *Queries) GetDiscountConditions(ctx context.Context, discountID int64) ([]DiscountCondition, error) {
	rows, err := q.db.Query(ctx, getDiscountConditions, discountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountCondition
	for rows.Next() {
		var i DiscountCondition
		if err := rows.Scan(
			&i.ID,
			&i.DiscountID,
			&i.ConditionType,
			&i.Operator,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscountCondition = `-- name: UpdateDiscountCondition :exec
UPDATE discount_conditions
SET
  condition_type = $2,
  value = $3
WHERE id = $1
`

type UpdateDiscountConditionParams struct {
	ID            int64  `json:"id"`
	ConditionType string `json:"condition_type"`
	Value         string `json:"value"`
}

func (q *Queries) UpdateDiscountCondition(ctx context.Context, arg UpdateDiscountConditionParams) error {
	_, err := q.db.Exec(ctx, updateDiscountCondition, arg.ID, arg.ConditionType, arg.Value)
	return err
}
