// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount-target.sql

package product_db

import (
	"context"
)

const bulkDeleteDiscountTargets = `-- name: BulkDeleteDiscountTargets :exec
DELETE FROM discount_targets
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteDiscountTargets(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteDiscountTargets, dollar_1)
	return err
}

const bulkInsertDiscountTargets = `-- name: BulkInsertDiscountTargets :exec
INSERT INTO discount_targets (discount_id, target_type, target_id)
SELECT
unnest($1::bigint[]),
unnest($2::text[]),
unnest($3::bigint[])
`

type BulkInsertDiscountTargetsParams struct {
	DiscountIds []int64  `json:"discount_ids"`
	TargetTypes []string `json:"target_types"`
	TargetIds   []int64  `json:"target_ids"`
}

func (q *Queries) BulkInsertDiscountTargets(ctx context.Context, arg BulkInsertDiscountTargetsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertDiscountTargets, arg.DiscountIds, arg.TargetTypes, arg.TargetIds)
	return err
}

const createDiscountTarget = `-- name: CreateDiscountTarget :one
INSERT INTO discount_targets (
  discount_id, target_type, target_id
)
VALUES ($1, $2, $3)
RETURNING id, discount_id, target_type, target_id
`

type CreateDiscountTargetParams struct {
	DiscountID int64  `json:"discount_id"`
	TargetType string `json:"target_type"`
	TargetID   int32  `json:"target_id"`
}

func (q *Queries) CreateDiscountTarget(ctx context.Context, arg CreateDiscountTargetParams) (DiscountTarget, error) {
	row := q.db.QueryRow(ctx, createDiscountTarget, arg.DiscountID, arg.TargetType, arg.TargetID)
	var i DiscountTarget
	err := row.Scan(
		&i.ID,
		&i.DiscountID,
		&i.TargetType,
		&i.TargetID,
	)
	return i, err
}

const getDiscountTargets = `-- name: GetDiscountTargets :many
SELECT id, discount_id, target_type, target_id FROM discount_targets WHERE discount_id = $1
`

func (q *Queries) GetDiscountTargets(ctx context.Context, discountID int64) ([]DiscountTarget, error) {
	rows, err := q.db.Query(ctx, getDiscountTargets, discountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountTarget
	for rows.Next() {
		var i DiscountTarget
		if err := rows.Scan(
			&i.ID,
			&i.DiscountID,
			&i.TargetType,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscountTarget = `-- name: UpdateDiscountTarget :exec
UPDATE discount_targets
SET
  target_type = $2,
  target_id = $3
WHERE id = $1
`

type UpdateDiscountTargetParams struct {
	ID         int64  `json:"id"`
	TargetType string `json:"target_type"`
	TargetID   int32  `json:"target_id"`
}

func (q *Queries) UpdateDiscountTarget(ctx context.Context, arg UpdateDiscountTargetParams) error {
	_, err := q.db.Exec(ctx, updateDiscountTarget, arg.ID, arg.TargetType, arg.TargetID)
	return err
}
