// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount_effect.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteDiscountEffects = `-- name: BulkDeleteDiscountEffects :exec
DELETE FROM discount_effects
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteDiscountEffects(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteDiscountEffects, dollar_1)
	return err
}

const createDiscountEffect = `-- name: CreateDiscountEffect :one
INSERT INTO discount_effects (
  discount_id, effect_type, value, applies_to
)
VALUES ($1, $2, $3, $4)
RETURNING id, discount_id, effect_type, value, applies_to
`

type CreateDiscountEffectParams struct {
	DiscountID int64       `json:"discount_id"`
	EffectType string      `json:"effect_type"`
	Value      pgtype.Text `json:"value"`
	AppliesTo  string      `json:"applies_to"`
}

func (q *Queries) CreateDiscountEffect(ctx context.Context, arg CreateDiscountEffectParams) (DiscountEffect, error) {
	row := q.db.QueryRow(ctx, createDiscountEffect,
		arg.DiscountID,
		arg.EffectType,
		arg.Value,
		arg.AppliesTo,
	)
	var i DiscountEffect
	err := row.Scan(
		&i.ID,
		&i.DiscountID,
		&i.EffectType,
		&i.Value,
		&i.AppliesTo,
	)
	return i, err
}

const getDiscountEffects = `-- name: GetDiscountEffects :many
SELECT id, discount_id, effect_type, value, applies_to FROM discount_effects WHERE discount_id = $1
`

func (q *Queries) GetDiscountEffects(ctx context.Context, discountID int64) ([]DiscountEffect, error) {
	rows, err := q.db.Query(ctx, getDiscountEffects, discountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountEffect
	for rows.Next() {
		var i DiscountEffect
		if err := rows.Scan(
			&i.ID,
			&i.DiscountID,
			&i.EffectType,
			&i.Value,
			&i.AppliesTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscountEffect = `-- name: UpdateDiscountEffect :exec
UPDATE discount_effects
SET
  effect_type = $2,
  value = $3,
  applies_to = $4
WHERE id = $1
`

type UpdateDiscountEffectParams struct {
	ID         int64       `json:"id"`
	EffectType string      `json:"effect_type"`
	Value      pgtype.Text `json:"value"`
	AppliesTo  string      `json:"applies_to"`
}

func (q *Queries) UpdateDiscountEffect(ctx context.Context, arg UpdateDiscountEffectParams) error {
	_, err := q.db.Exec(ctx, updateDiscountEffect,
		arg.ID,
		arg.EffectType,
		arg.Value,
		arg.AppliesTo,
	)
	return err
}
