// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount_customer.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerUsage = `-- name: GetCustomerUsage :one
SELECT used_count FROM discount_customer_usages WHERE discount_id = $1 AND customer_id = $2
`

type GetCustomerUsageParams struct {
	DiscountID int64 `json:"discount_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) GetCustomerUsage(ctx context.Context, arg GetCustomerUsageParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getCustomerUsage, arg.DiscountID, arg.CustomerID)
	var used_count pgtype.Int4
	err := row.Scan(&used_count)
	return used_count, err
}

const upsertCustomerUsage = `-- name: UpsertCustomerUsage :exec
INSERT INTO discount_customer_usages (discount_id, customer_id, used_count)
VALUES ($1, $2, 1)
ON CONFLICT (discount_id, customer_id) DO UPDATE
SET used_count = discount_customer_usages.used_count + 1
`

type UpsertCustomerUsageParams struct {
	DiscountID int64 `json:"discount_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) UpsertCustomerUsage(ctx context.Context, arg UpsertCustomerUsageParams) error {
	_, err := q.db.Exec(ctx, upsertCustomerUsage, arg.DiscountID, arg.CustomerID)
	return err
}
