// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package product_db

import (
	"context"
)

const bulkDeleteFiles = `-- name: BulkDeleteFiles :exec
DELETE FROM files
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeleteFiles(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteFiles, dollar_1)
	return err
}

const bulkInsertFiles = `-- name: BulkInsertFiles :exec
INSERT INTO
  files (
    name
  )
SELECT
  unnest($1::text[]) as name
`

func (q *Queries) BulkInsertFiles(ctx context.Context, names []string) error {
	_, err := q.db.Exec(ctx, bulkInsertFiles, names)
	return err
}

const countFiles = `-- name: CountFiles :one
SELECT
  COUNT(*)
FROM
  files
`

func (q *Queries) CountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFiles = `-- name: GetFiles :many
SELECT
  id, name
FROM
  files
ORDER BY
  created_at DESC
LIMIT
  $1
OFFSET
  $2
`

type GetFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetFilesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetFiles(ctx context.Context, arg GetFilesParams) ([]GetFilesRow, error) {
	rows, err := q.db.Query(ctx, getFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesRow
	for rows.Next() {
		var i GetFilesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
