// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package product_db

import (
	"context"
)

const bulkDeleteMenus = `-- name: BulkDeleteMenus :exec
DELETE FROM menus
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeleteMenus(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteMenus, dollar_1)
	return err
}

const countMenus = `-- name: CountMenus :one
SELECT
  COUNT(*)
FROM
  menus
`

func (q *Queries) CountMenus(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMenus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO
  menus (name, position)
VALUES
  ($1, $2)
RETURNING
  id
`

type CreateMenuParams struct {
	Name     string `json:"name"`
	Position string `json:"position"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMenu, arg.Name, arg.Position)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMenu = `-- name: GetMenu :one
SELECT
  id,
  name,
  position
FROM
  menus
WHERE
  id = $1
`

type GetMenuRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position string `json:"position"`
}

func (q *Queries) GetMenu(ctx context.Context, id int64) (GetMenuRow, error) {
	row := q.db.QueryRow(ctx, getMenu, id)
	var i GetMenuRow
	err := row.Scan(&i.ID, &i.Name, &i.Position)
	return i, err
}

const getMenuByPosition = `-- name: GetMenuByPosition :one
SELECT
  id,
  name,
  position
FROM
  menus
WHERE
  position = $1
`

type GetMenuByPositionRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position string `json:"position"`
}

func (q *Queries) GetMenuByPosition(ctx context.Context, position string) (GetMenuByPositionRow, error) {
	row := q.db.QueryRow(ctx, getMenuByPosition, position)
	var i GetMenuByPositionRow
	err := row.Scan(&i.ID, &i.Name, &i.Position)
	return i, err
}

const getMenus = `-- name: GetMenus :many
SELECT
  id,
  name,
  position
FROM
  menus
LIMIT
  $1
OFFSET
  $2
`

type GetMenusParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetMenusRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position string `json:"position"`
}

func (q *Queries) GetMenus(ctx context.Context, arg GetMenusParams) ([]GetMenusRow, error) {
	rows, err := q.db.Query(ctx, getMenus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMenusRow
	for rows.Next() {
		var i GetMenusRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :exec
UPDATE menus
SET
  name = $2,
  position = $3
WHERE
  id = $1
`

type UpdateMenuParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position string `json:"position"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) error {
	_, err := q.db.Exec(ctx, updateMenu, arg.ID, arg.Name, arg.Position)
	return err
}
