// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID          int64       `json:"id"`
	UserID      pgtype.Int4 `json:"user_id"`
	FullName    string      `json:"full_name"`
	AddressLine string      `json:"address_line"`
	City        pgtype.Text `json:"city"`
	State       pgtype.Text `json:"state"`
	Country     pgtype.Text `json:"country"`
	PostalCode  pgtype.Text `json:"postal_code"`
	Phone       pgtype.Text `json:"phone"`
}

type Category struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	ParentID  pgtype.Int8      `json:"parent_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Collection struct {
	ID              int64            `json:"id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	File            pgtype.Text      `json:"file"`
	IsFeatured      pgtype.Bool      `json:"is_featured"`
	MetaTitle       pgtype.Text      `json:"meta_title"`
	MetaDescription pgtype.Text      `json:"meta_description"`
	MetaKeywords    pgtype.Text      `json:"meta_keywords"`
	CanonicalUrl    pgtype.Text      `json:"canonical_url"`
	OgTitle         pgtype.Text      `json:"og_title"`
	OgDescription   pgtype.Text      `json:"og_description"`
	OgImage         pgtype.Text      `json:"og_image"`
	Layout          pgtype.Text      `json:"layout"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Coupon struct {
	ID              int64            `json:"id"`
	Code            string           `json:"code"`
	Description     pgtype.Text      `json:"description"`
	DiscountPercent interface{}      `json:"discount_percent"`
	ValidFrom       pgtype.Timestamp `json:"valid_from"`
	ValidUntil      pgtype.Timestamp `json:"valid_until"`
	IsActive        pgtype.Bool      `json:"is_active"`
}

type Customer struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Avatar    pgtype.Text      `json:"avatar"`
	Email     pgtype.Text      `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type File struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Option struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	No        int32  `json:"no"`
	ProductID int64  `json:"product_id"`
}

type OptionValue struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	No       pgtype.Int4 `json:"no"`
	OptionID int64       `json:"option_id"`
}

type Order struct {
	ID                int64            `json:"id"`
	TotalAmount       int32            `json:"total_amount"`
	DiscountAmount    int32            `json:"discount_amount"`
	ShippingAddressID pgtype.Int8      `json:"shipping_address_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID        int64       `json:"id"`
	Quantity  int32       `json:"quantity"`
	SalePrice int32       `json:"sale_price"`
	OrderID   int64       `json:"order_id"`
	ProductID pgtype.Int8 `json:"product_id"`
	VariantID pgtype.Int8 `json:"variant_id"`
}

type Product struct {
	ID              int64            `json:"id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	OriginPrice     int32            `json:"origin_price"`
	SalePrice       int32            `json:"sale_price"`
	MetaTitle       string           `json:"meta_title"`
	MetaDescription string           `json:"meta_description"`
	MetaKeywords    string           `json:"meta_keywords"`
	CanonicalUrl    string           `json:"canonical_url"`
	OgTitle         string           `json:"og_title"`
	OgDescription   string           `json:"og_description"`
	OgImage         string           `json:"og_image"`
	IsActive        bool             `json:"is_active"`
	CategoryID      pgtype.Int8      `json:"category_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ProductCollection struct {
	ProductID    int64 `json:"product_id"`
	CollectionID int64 `json:"collection_id"`
}

type ProductFile struct {
	Name      pgtype.Text `json:"name"`
	No        int32       `json:"no"`
	IsPrimary bool        `json:"is_primary"`
	ProductID int64       `json:"product_id"`
}

type ProductTag struct {
	Name      string `json:"name"`
	ProductID int64  `json:"product_id"`
}

type Review struct {
	ID         int64            `json:"id"`
	ProductID  pgtype.Int8      `json:"product_id"`
	Rating     pgtype.Int4      `json:"rating"`
	Comment    pgtype.Text      `json:"comment"`
	HasFile    bool             `json:"has_file"`
	CustomerID int64            `json:"customer_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type ReviewFile struct {
	Name     string `json:"name"`
	ReviewID int64  `json:"review_id"`
}

type Variant struct {
	ID          int64       `json:"id"`
	OriginPrice int32       `json:"origin_price"`
	SalePrice   int32       `json:"sale_price"`
	File        pgtype.Text `json:"file"`
	Stock       int32       `json:"stock"`
	Sku         string      `json:"sku"`
	No          int32       `json:"no"`
	ProductID   int64       `json:"product_id"`
}

type VariantOption struct {
	VariantID     int64 `json:"variant_id"`
	OptionValueID int64 `json:"option_value_id"`
	OptionID      int64 `json:"option_id"`
}
