// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteOrders = `-- name: BulkDeleteOrders :exec
DELETE FROM orders
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeleteOrders(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteOrders, dollar_1)
	return err
}

const checkOrderCreated = `-- name: CheckOrderCreated :one
SELECT
  id
FROM
  orders
WHERE
  id = $1
`

func (q *Queries) CheckOrderCreated(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, checkOrderCreated, id)
	err := row.Scan(&id)
	return id, err
}

const countOrders = `-- name: CountOrders :one
SELECT
  COUNT(*)
FROM
  orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
  orders (
    total_amount,
    discount_amount,
    shipping_address_id
  )
VALUES
  ($1, $2, $3)
RETURNING
  id
`

type CreateOrderParams struct {
	TotalAmount       int32       `json:"total_amount"`
	DiscountAmount    int32       `json:"discount_amount"`
	ShippingAddressID pgtype.Int8 `json:"shipping_address_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.TotalAmount, arg.DiscountAmount, arg.ShippingAddressID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrder = `-- name: GetOrder :one
SELECT
  o.total_amount,
  o.discount_amount,
  a.full_name,
  a.phone,
  a.address_line
FROM
  orders o
  LEFT JOIN addresses a ON o.shipping_address_id = a.id
WHERE
  o.id = $1
`

type GetOrderRow struct {
	TotalAmount    int32       `json:"total_amount"`
	DiscountAmount int32       `json:"discount_amount"`
	FullName       pgtype.Text `json:"full_name"`
	Phone          pgtype.Text `json:"phone"`
	AddressLine    pgtype.Text `json:"address_line"`
}

func (q *Queries) GetOrder(ctx context.Context, id int64) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.FullName,
		&i.Phone,
		&i.AddressLine,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT
  id,
  total_amount,
  discount_amount,
  created_at
FROM
  orders
LIMIT
  $1
OFFSET
  $2
`

type GetOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetOrdersRow struct {
	ID             int64            `json:"id"`
	TotalAmount    int32            `json:"total_amount"`
	DiscountAmount int32            `json:"discount_amount"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetOrders(ctx context.Context, arg GetOrdersParams) ([]GetOrdersRow, error) {
	rows, err := q.db.Query(ctx, getOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersRow
	for rows.Next() {
		var i GetOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
