// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order-item.sql

package product_db

import (
	"context"
)

const bulkInsertOrderItems = `-- name: BulkInsertOrderItems :exec
INSERT INTO
  order_items (
    quantity,
    sale_price,
    order_id,
    product_id,
    variant_id
  )
SELECT
  UNNEST($1::int[]),
  UNNEST($2::int[]),
  UNNEST($3::bigint[]),
  UNNEST($4::bigint[]),
  UNNEST($5::bigint[])
`

type BulkInsertOrderItemsParams struct {
	Quantities []int32 `json:"quantities"`
	SalePrices []int32 `json:"sale_prices"`
	OrderIds   []int64 `json:"order_ids"`
	ProductIds []int64 `json:"product_ids"`
	VariantIds []int64 `json:"variant_ids"`
}

func (q *Queries) BulkInsertOrderItems(ctx context.Context, arg BulkInsertOrderItemsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertOrderItems,
		arg.Quantities,
		arg.SalePrices,
		arg.OrderIds,
		arg.ProductIds,
		arg.VariantIds,
	)
	return err
}
