// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order-item.sql

package product_db

import (
	"context"
)

const bulkInsertOrderItems = `-- name: BulkInsertOrderItems :exec
INSERT INTO
  order_items (
    quantity,
    sale_price,
    order_id,
    product_id,
    variant_id
  )
SELECT
  UNNEST($1::int[]),
  UNNEST($2::int[]),
  UNNEST($3::bigint[]),
  UNNEST($4::bigint[]),
  UNNEST($5::bigint[])
`

type BulkInsertOrderItemsParams struct {
	Quantities []int32 `json:"quantities"`
	SalePrices []int32 `json:"sale_prices"`
	OrderIds   []int64 `json:"order_ids"`
	ProductIds []int64 `json:"product_ids"`
	VariantIds []int64 `json:"variant_ids"`
}

func (q *Queries) BulkInsertOrderItems(ctx context.Context, arg BulkInsertOrderItemsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertOrderItems,
		arg.Quantities,
		arg.SalePrices,
		arg.OrderIds,
		arg.ProductIds,
		arg.VariantIds,
	)
	return err
}

const getItemsByOrderID = `-- name: GetItemsByOrderID :many
SELECT
  oi.id AS order_item_id,
  oi.quantity,
  oi.sale_price,
  p.id AS product_id,
  p.name,
  p.slug,
  jsonb_object_agg(o.name, ov.name) AS options
FROM
  order_items oi
  JOIN products p ON oi.product_id = p.id
  JOIN variants v ON oi.variant_id = v.id
  JOIN variant_options vo ON vo.variant_id = v.id
  JOIN options o ON o.id = vo.option_id
  JOIN option_values ov ON ov.id = vo.option_value_id
WHERE
  oi.order_id = $1
GROUP BY
  oi.id,
  p.id,
  p.name,
  p.slug,
  oi.quantity,
  oi.sale_price
ORDER BY
  oi.id
`

type GetItemsByOrderIDRow struct {
	OrderItemID int64  `json:"order_item_id"`
	Quantity    int32  `json:"quantity"`
	SalePrice   int32  `json:"sale_price"`
	ProductID   int64  `json:"product_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Options     []byte `json:"options"`
}

func (q *Queries) GetItemsByOrderID(ctx context.Context, orderID int64) ([]GetItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByOrderIDRow
	for rows.Next() {
		var i GetItemsByOrderIDRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.Quantity,
			&i.SalePrice,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
