// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page.sql

package product_db

import (
	"context"
)

const bulkDeletePages = `-- name: BulkDeletePages :exec
DELETE FROM pages
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeletePages(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeletePages, dollar_1)
	return err
}

const countPages = `-- name: CountPages :one
SELECT
  COUNT(*)
FROM
  pages
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO
  pages (name, slug)
VALUES
  ($1, $2)
RETURNING id
`

type CreatePageParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPage, arg.Name, arg.Slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPage = `-- name: GetPage :one
SELECT id, name, slug
FROM pages
WHERE id = $1
`

type GetPageRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetPage(ctx context.Context, id int64) (GetPageRow, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i GetPageRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, name, slug
FROM pages
WHERE slug = $1
`

type GetPageBySlugRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (GetPageBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i GetPageBySlugRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getPages = `-- name: GetPages :many
SELECT id, name, slug
FROM pages
LIMIT
  $1
OFFSET
  $2
`

type GetPagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPagesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetPages(ctx context.Context, arg GetPagesParams) ([]GetPagesRow, error) {
	rows, err := q.db.Query(ctx, getPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPagesRow
	for rows.Next() {
		var i GetPagesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages
SET
  name = $2,
  slug = $3
WHERE
  id = $1
`

type UpdatePageParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.Exec(ctx, updatePage, arg.ID, arg.Name, arg.Slug)
	return err
}
