// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product-hostspot.sql

package product_db

import (
	"context"
)

const bulkDeleteProductHotspots = `-- name: BulkDeleteProductHotspots :exec
DELETE FROM product_hotspots
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteProductHotspots(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteProductHotspots, dollar_1)
	return err
}

const bulkInsertProductHotspots = `-- name: BulkInsertProductHotspots :exec
INSERT INTO
  product_hotspots (x, y, product_id, hotspot_id)
SELECT
  unnest($1::real[]) as x,
  unnest($2::real[]) as y,
  unnest($3::bigint[]) as product_id,
  unnest($4::bigint[]) as hotspot_id
`

type BulkInsertProductHotspotsParams struct {
	Xs         []float32 `json:"xs"`
	Ys         []float32 `json:"ys"`
	ProductIds []int64   `json:"product_ids"`
	HotspotIds []int64   `json:"hotspot_ids"`
}

func (q *Queries) BulkInsertProductHotspots(ctx context.Context, arg BulkInsertProductHotspotsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertProductHotspots,
		arg.Xs,
		arg.Ys,
		arg.ProductIds,
		arg.HotspotIds,
	)
	return err
}

const bulkUpdateProductHotspots = `-- name: BulkUpdateProductHotspots :exec
UPDATE product_hotspots ph
SET product_id = u.product_id
FROM (
    SELECT
        unnest($1::bigint[]) AS hotspot_id,
        unnest($2::bigint[]) AS product_id
) AS u
WHERE ph.hotspot_id = u.hotspot_id
`

type BulkUpdateProductHotspotsParams struct {
	HotspotIds []int64 `json:"hotspot_ids"`
	ProductIds []int64 `json:"product_ids"`
}

func (q *Queries) BulkUpdateProductHotspots(ctx context.Context, arg BulkUpdateProductHotspotsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateProductHotspots, arg.HotspotIds, arg.ProductIds)
	return err
}

const getProductHotspotsByHotspot = `-- name: GetProductHotspotsByHotspot :many
SELECT id
FROM product_hotspots
WHERE hotspot_id = $1
`

func (q *Queries) GetProductHotspotsByHotspot(ctx context.Context, hotspotID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getProductHotspotsByHotspot, hotspotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
