// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product-hostspot.sql

package product_db

import (
	"context"
)

const bulkDeleteProductHotspots = `-- name: BulkDeleteProductHotspots :exec
DELETE FROM product_hotspots
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteProductHotspots(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteProductHotspots, dollar_1)
	return err
}

const bulkInsertProductHotspots = `-- name: BulkInsertProductHotspots :exec
INSERT INTO
  product_hotspots (x, y, product_id, hotspot_id)
SELECT
  unnest($1::real[]) as x,
  unnest($2::real[]) as y,
  unnest($3::bigint[]) as product_id,
  unnest($4::bigint[]) as hotspot_id
`

type BulkInsertProductHotspotsParams struct {
	Xs         []float32 `json:"xs"`
	Ys         []float32 `json:"ys"`
	ProductIds []int64   `json:"product_ids"`
	HotspotIds []int64   `json:"hotspot_ids"`
}

func (q *Queries) BulkInsertProductHotspots(ctx context.Context, arg BulkInsertProductHotspotsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertProductHotspots,
		arg.Xs,
		arg.Ys,
		arg.ProductIds,
		arg.HotspotIds,
	)
	return err
}

const bulkUpdateProductHotspots = `-- name: BulkUpdateProductHotspots :exec
UPDATE product_hotspots ph
SET product_id = u.product_id
FROM (
    SELECT
        unnest($1::bigint[]) AS hotspot_id,
        unnest($2::bigint[]) AS product_id
) AS u
WHERE ph.hotspot_id = u.hotspot_id
`

type BulkUpdateProductHotspotsParams struct {
	HotspotIds []int64 `json:"hotspot_ids"`
	ProductIds []int64 `json:"product_ids"`
}

func (q *Queries) BulkUpdateProductHotspots(ctx context.Context, arg BulkUpdateProductHotspotsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateProductHotspots, arg.HotspotIds, arg.ProductIds)
	return err
}

const getHotspotByProduct = `-- name: GetHotspotByProduct :many
SELECT h.id, h.file,
  COALESCE(
    json_agg(
      json_build_object(
        'id', ph.id,
        'product_id', ph.product_id,
        'x', ph.x,
        'y', ph.y,
        'product', json_build_object(
          'id', p.id,
          'name', p.name,
          'slug', p.slug,
          'origin_price', p.origin_price,
          'sale_price', p.sale_price,
          'file', f.name
        )
      )
    ) FILTER (WHERE ph.id IS NOT NULL),
    '[]'
  ) AS spots
FROM hotspots h
JOIN product_hotspots ph ON ph.hotspot_id = h.id
LEFT JOIN products p ON p.id = ph.product_id
LEFT JOIN LATERAL (
  SELECT
    name
  FROM
    product_files
  WHERE
    product_id = p.id
    AND is_primary = true
  LIMIT
    1
) f ON true
WHERE ph.product_id = $1
GROUP BY h.id, h.file
`

type GetHotspotByProductRow struct {
	ID    int64       `json:"id"`
	File  string      `json:"file"`
	Spots interface{} `json:"spots"`
}

func (q *Queries) GetHotspotByProduct(ctx context.Context, productID int64) ([]GetHotspotByProductRow, error) {
	rows, err := q.db.Query(ctx, getHotspotByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHotspotByProductRow
	for rows.Next() {
		var i GetHotspotByProductRow
		if err := rows.Scan(&i.ID, &i.File, &i.Spots); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductHotspotsByHotspot = `-- name: GetProductHotspotsByHotspot :many
SELECT id
FROM product_hotspots
WHERE hotspot_id = $1
`

func (q *Queries) GetProductHotspotsByHotspot(ctx context.Context, hotspotID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getProductHotspotsByHotspot, hotspotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
