// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product-collection.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertProductCollection = `-- name: BulkInsertProductCollection :exec
INSERT INTO
  product_collections (product_id, collection_id)
SELECT
  unnest($1::bigint[]),
  unnest($2::bigint[])
`

type BulkInsertProductCollectionParams struct {
	ProductIds    []int64 `json:"product_ids"`
	CollectionIds []int64 `json:"collection_ids"`
}

func (q *Queries) BulkInsertProductCollection(ctx context.Context, arg BulkInsertProductCollectionParams) error {
	_, err := q.db.Exec(ctx, bulkInsertProductCollection, arg.ProductIds, arg.CollectionIds)
	return err
}

const deleteProductCollections = `-- name: DeleteProductCollections :exec
DELETE FROM product_collections WHERE product_id = $1
`

func (q *Queries) DeleteProductCollections(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, deleteProductCollections, productID)
	return err
}

const getCollectionsByProductID = `-- name: GetCollectionsByProductID :many
SELECT
  c.id,
  c.name
FROM
  product_collections pc
  LEFT JOIN collections c ON pc.collection_id = c.id
WHERE
  product_id = $1
`

type GetCollectionsByProductIDRow struct {
	ID   pgtype.Int8 `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) GetCollectionsByProductID(ctx context.Context, productID int64) ([]GetCollectionsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getCollectionsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionsByProductIDRow
	for rows.Next() {
		var i GetCollectionsByProductIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
