// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review-file.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertReviewFiles = `-- name: BulkInsertReviewFiles :exec
INSERT INTO
  review_files (name, review_id)
SELECT
  unnest($1::text[]),
  unnest($2::bigint[])
`

type BulkInsertReviewFilesParams struct {
	Names     []string `json:"names"`
	ReviewIds []int64  `json:"review_ids"`
}

func (q *Queries) BulkInsertReviewFiles(ctx context.Context, arg BulkInsertReviewFilesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertReviewFiles, arg.Names, arg.ReviewIds)
	return err
}

const countReviewFilesByProduct = `-- name: CountReviewFilesByProduct :one
SELECT
  COUNT(*)
FROM
  review_files rf
JOIN reviews r ON r.id = rf.review_id
WHERE r.product_id = $1
`

func (q *Queries) CountReviewFilesByProduct(ctx context.Context, productID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewFilesByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewFilesByProduct = `-- name: GetReviewFilesByProduct :many
SELECT rf.name
FROM
  review_files rf
JOIN reviews r ON r.id = rf.review_id
WHERE r.product_id = $1
LIMIT 8
OFFSET 0
`

func (q *Queries) GetReviewFilesByProduct(ctx context.Context, productID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, getReviewFilesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
