// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipping-fee.sql

package product_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteShippingFees = `-- name: BulkDeleteShippingFees :exec
DELETE FROM shipping_fees
WHERE
  id = ANY ($1::bigint[])
`

func (q *Queries) BulkDeleteShippingFees(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteShippingFees, dollar_1)
	return err
}

const countShippingFees = `-- name: CountShippingFees :one
SELECT
  COUNT(*)
FROM
  shipping_fees
`

func (q *Queries) CountShippingFees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countShippingFees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShippingFee = `-- name: CreateShippingFee :one
INSERT INTO
  shipping_fees (
  name,
  min_weight,
  max_weight,
  fee_amount,
  min_order_value,
  free_shipping
  )
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING
  id
`

type CreateShippingFeeParams struct {
	Name          pgtype.Text `json:"name"`
	MinWeight     int32       `json:"min_weight"`
	MaxWeight     int32       `json:"max_weight"`
	FeeAmount     int32       `json:"fee_amount"`
	MinOrderValue pgtype.Int4 `json:"min_order_value"`
	FreeShipping  pgtype.Bool `json:"free_shipping"`
}

func (q *Queries) CreateShippingFee(ctx context.Context, arg CreateShippingFeeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createShippingFee,
		arg.Name,
		arg.MinWeight,
		arg.MaxWeight,
		arg.FeeAmount,
		arg.MinOrderValue,
		arg.FreeShipping,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getShippingFee = `-- name: GetShippingFee :one
SELECT
  id,
  name,
  min_weight,
  max_weight,
  fee_amount,
  min_order_value,
  free_shipping
FROM
  shipping_fees
WHERE
  id = $1
LIMIT
  1
`

type GetShippingFeeRow struct {
	ID            int64       `json:"id"`
	Name          pgtype.Text `json:"name"`
	MinWeight     int32       `json:"min_weight"`
	MaxWeight     int32       `json:"max_weight"`
	FeeAmount     int32       `json:"fee_amount"`
	MinOrderValue pgtype.Int4 `json:"min_order_value"`
	FreeShipping  pgtype.Bool `json:"free_shipping"`
}

func (q *Queries) GetShippingFee(ctx context.Context, id int64) (GetShippingFeeRow, error) {
	row := q.db.QueryRow(ctx, getShippingFee, id)
	var i GetShippingFeeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinWeight,
		&i.MaxWeight,
		&i.FeeAmount,
		&i.MinOrderValue,
		&i.FreeShipping,
	)
	return i, err
}

const getShippingFeeByWeight = `-- name: GetShippingFeeByWeight :one
SELECT
  id,
  name,
  min_weight,
  max_weight,
  fee_amount,
  min_order_value,
  free_shipping
FROM
  shipping_fees
WHERE
  $1 >= min_weight
  AND $1 < max_weight
ORDER BY
  max_weight ASC
LIMIT 1
`

type GetShippingFeeByWeightRow struct {
	ID            int64       `json:"id"`
	Name          pgtype.Text `json:"name"`
	MinWeight     int32       `json:"min_weight"`
	MaxWeight     int32       `json:"max_weight"`
	FeeAmount     int32       `json:"fee_amount"`
	MinOrderValue pgtype.Int4 `json:"min_order_value"`
	FreeShipping  pgtype.Bool `json:"free_shipping"`
}

func (q *Queries) GetShippingFeeByWeight(ctx context.Context, minWeight int32) (GetShippingFeeByWeightRow, error) {
	row := q.db.QueryRow(ctx, getShippingFeeByWeight, minWeight)
	var i GetShippingFeeByWeightRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinWeight,
		&i.MaxWeight,
		&i.FeeAmount,
		&i.MinOrderValue,
		&i.FreeShipping,
	)
	return i, err
}

const getShippingFees = `-- name: GetShippingFees :many
SELECT
  id,
  name,
  min_weight,
  max_weight,
  fee_amount,
  min_order_value,
  free_shipping
FROM
  shipping_fees
ORDER BY
  min_weight ASC
LIMIT
  $1
OFFSET
  $2
`

type GetShippingFeesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetShippingFeesRow struct {
	ID            int64       `json:"id"`
	Name          pgtype.Text `json:"name"`
	MinWeight     int32       `json:"min_weight"`
	MaxWeight     int32       `json:"max_weight"`
	FeeAmount     int32       `json:"fee_amount"`
	MinOrderValue pgtype.Int4 `json:"min_order_value"`
	FreeShipping  pgtype.Bool `json:"free_shipping"`
}

func (q *Queries) GetShippingFees(ctx context.Context, arg GetShippingFeesParams) ([]GetShippingFeesRow, error) {
	rows, err := q.db.Query(ctx, getShippingFees, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShippingFeesRow
	for rows.Next() {
		var i GetShippingFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MinWeight,
			&i.MaxWeight,
			&i.FeeAmount,
			&i.MinOrderValue,
			&i.FreeShipping,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShippingFee = `-- name: UpdateShippingFee :exec
UPDATE shipping_fees
SET
  min_weight = $2,
  max_weight = $3,
  fee_amount = $4,
  min_order_value = $5,
  free_shipping = $6,
  name = $7
WHERE
  id = $1
`

type UpdateShippingFeeParams struct {
	ID            int64       `json:"id"`
	MinWeight     int32       `json:"min_weight"`
	MaxWeight     int32       `json:"max_weight"`
	FeeAmount     int32       `json:"fee_amount"`
	MinOrderValue pgtype.Int4 `json:"min_order_value"`
	FreeShipping  pgtype.Bool `json:"free_shipping"`
	Name          pgtype.Text `json:"name"`
}

func (q *Queries) UpdateShippingFee(ctx context.Context, arg UpdateShippingFeeParams) error {
	_, err := q.db.Exec(ctx, updateShippingFee,
		arg.ID,
		arg.MinWeight,
		arg.MaxWeight,
		arg.FeeAmount,
		arg.MinOrderValue,
		arg.FreeShipping,
		arg.Name,
	)
	return err
}
